Repository codeit-plake/plake, pull requests merged in 2025-04, with the labels that each got.

#126 [#113]refactor: 모임 삭제 후 이전 페이지로 이동 + 모임 생성 모달 동작 변경
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useCreateGathering.ts
Labels: refactor

#137 [#6]chore: Sentry 설정 파일 추가
  .github/workflows/mirror-and-deploy.yml
  .github/workflows/pr-quality-checks.yml
Labels: chore

#136 [#135]feature: sentry 연동[PLAK-186]
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  src/instrumentation-client.ts
  src/instrumentation.ts
Labels: feature

#141 [#139]test: jest test coverage 측정을 위한 config 파일 변경[PLAK-187]
  jest.config.ts
  package.json
Labels: test

#142 [#132]test: Header,Input 컴포넌트 테스트
  jest.config.ts
  jest.setup.ts
  src/app/all-reviews/[tab]/_components/ReviewListParent.tsx
  src/app/mypage/_components/my-card-list/MyWrittenCardList.tsx
  src/components/common/tests/.gitkeep
  src/components/common/tests/Avatar.test.tsx
  src/components/layout/Header.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/layout/tests/.gitkeep
  src/components/layout/tests/Header.test.tsx
  src/components/ui/tests/.gitkeep
  src/components/ui/tests/Input.test.tsx
  src/hooks/review/useReviewList.ts
  src/utils/test-utils/userMocking.ts
Labels: test

#145 [#67]refactor: PolymorphicHttpClient 작성 및 공통 로직 BaseHttpClient로 분리
  src/hooks/auth/useUpdateUser.ts
  src/hooks/gathering/useCreateGathering.ts
  src/services/BaseHttpClient.ts
  src/services/HttpClient.ts
  src/services/PolymorphicHttpClient.ts
  src/services/Service.ts
  src/services/auth/AuthService.ts
  src/services/gathering/GatheringService.ts
  src/services/review/ReviewService.ts
Labels: refactor

#147 [#30]test: 컴포넌트 및 훅 테스트 코드 작성
  jest.setup.ts
  src/app/(home)/_components/MainBanner.tsx
  src/components/common/tests/ProgressBar.test.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/DateTimeAndEndTimePicker.tsx
  src/components/ui/Calendar.tsx
  src/components/ui/CarouselArrowButton.tsx
  src/components/ui/DateTimePicker.tsx
  src/components/ui/ImageUploader.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/ServiceSelector.tsx
  src/components/ui/SubServiceSelector.tsx
  src/components/ui/TimePicker.tsx
  src/components/ui/tests/CarouselArrowButton.test.tsx
  src/components/ui/tests/DateTimePicker.test.tsx
  src/components/ui/tests/ImageUploader.test.tsx
  src/components/ui/tests/InViewSlide.test.tsx
  src/components/ui/tests/Pagination.test.tsx
  src/components/ui/tests/ServiceSelector.test.tsx
  src/components/ui/tests/SubServiceSelector.test.tsx
  src/components/ui/tests/TimePicker.test.tsx
  src/components/ui/tests/__snapshots__/CarouselArrowButton.test.tsx.snap
  src/components/ui/tests/__snapshots__/SubServiceSelector.test.tsx.snap
  src/components/ui/tests/__snapshots__/TimePicker.test.tsx.snap
  src/hooks/tests/useCalendar.test.ts
  src/hooks/tests/useCarouselEdge.test.ts
  src/hooks/tests/useClickOutside.test.ts
  src/hooks/tests/useCopyLink.test.ts
  src/hooks/tests/useScrollToTopOnValueChange.test.ts
  src/hooks/useCarouselEdge.ts
  src/hooks/useCopyLink.ts
Labels: test

#148 [#146]test: auth 훅 일부 리팩토링 및 테스트 코드 추가
  jest.config.ts
  src/components/common/tests/FavoriteButton.test.tsx
  src/constants/queryKeys.ts
  src/hooks/auth/tests/useCheckUser.test.ts
  src/hooks/auth/useCheckUser.ts
  src/hooks/auth/useUpdateUser.ts
  src/utils/myCardHelpers.tsx
  src/utils/test-utils/userMocking.ts
  src/utils/tests/myCardHelpers.test.tsx
Labels: test

#149 [#132]test: 공통 UI 컴포넌트 테스트
  jest.setup.ts
  src/components/common/tests/Avatar.test.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/layout/ReviewCardList.tsx
  src/components/layout/tests/Footer.test.tsx
  src/components/layout/tests/Header.test.tsx
  src/components/layout/tests/LoginJoinLayout.test.tsx
  src/components/layout/tests/ReviewCard.test.tsx
  src/components/navigations/tests/.gitkeep
  src/components/navigations/tests/NavList.test.tsx
  src/utils/test-utils/reviewMocking.ts
  src/utils/test-utils/userMocking.ts
Labels: test

#152 [#146]test: useMyGatheringList 훅 및 로딩 컴포넌트 리팩토링 및 테스트 코드 추가
  src/components/common/LoadingDots.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/tests/LoadingDots.test.tsx
  src/components/common/tests/LoadingSpinner.test.tsx
  src/components/common/tests/__snapshots__/LoadingDots.test.tsx.snap
  src/components/common/tests/__snapshots__/LoadingSpinner.test.tsx.snap
  src/hooks/gathering/tests/useMyGatheringList.test.ts
  src/hooks/gathering/useMyGatheringList.ts
  src/utils/test-utils/myGatheringMocking.ts
  src/utils/test-utils/reviewMocking.ts
Labels: refactor, test

#154 [#6]chore: Sentry 설정
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/sentry.client.config.ts
Labels: chore

#156 [#6]chore: Sentry 설정 및 main 브랜치 커밋 메세지 변경
  .github/workflows/mirror-and-deploy.yml
  sentry.client.config.ts
  src/app/mypage/_components/my-card-list/MyCardList.tsx
Labels: chore

#158 [#146]test: 마이페이지 비지니스 로직 테스트 코드 작성
  jest.config.ts
  src/app/mypage/_components/ReviewTab.tsx
  src/app/mypage/_components/my-card-item/MyCardAction.tsx
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/_components/my-card-list/MyCreateCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
  src/app/mypage/_components/tests/MyCardAction.test.tsx
  src/app/mypage/_components/tests/MyCardList.test.tsx
  src/app/mypage/_components/tests/MyCreateCardList.test.tsx
  src/app/mypage/_components/tests/MyReviewCardList.test.tsx
  src/app/mypage/_components/tests/MyWrittenCardList.test.tsx
  src/app/mypage/_components/tests/ReviewTab.test.tsx
  src/components/layout/ReviewCardItem.tsx
  src/constants/ui.ts
  src/hooks/review/tests/useCreateReview.test.tsx
  src/hooks/review/useCreateReview.ts
Labels: test

#159 [#143]test: 공통 컴포넌트 유닛 테스트 & 리팩토링
  src/app/favorites/_components/FavoriteFilterTab.tsx
  src/app/favorites/_components/FavoriteMainTab.tsx
  src/app/favorites/_components/FavoriteSubTab.tsx
  src/app/gathering/[tab]/_components/GatheringFilterTab.tsx
  src/app/gathering/[tab]/_components/GatheringMainTab.tsx
  src/app/gathering/[tab]/_components/GatheringSubTab.tsx
  src/app/gathering/[tab]/_components/tests/GatheringFilterTab.test.tsx
  src/app/gathering/[tab]/_components/tests/GatheringMainTab.test.tsx
  src/app/gathering/[tab]/_components/tests/GatheringSubTab.test.tsx
  src/app/gathering/[tab]/_components/tests/__snapshots__/GatheringFilterTab.test.tsx.snap
  src/app/gathering/[tab]/layout.tsx
  src/app/gathering/detail/[id]/_components/GatheringImage.tsx
  src/components/common/DeadlineTag.tsx
  src/components/common/stories/DeadlineTag.stories.tsx
  src/components/common/tests/DeadlineTag.test.tsx
  src/components/common/tests/Dropdown.test.tsx
  src/components/common/tests/SortDropdown.test.tsx
  src/components/layout/MainCardItem.tsx
  src/components/navigations/MainTab.tsx
  src/components/navigations/stories/MainTab.stories.tsx
  src/components/navigations/stories/SubTab.stories.tsx
  src/components/navigations/tests/FilterTab.test.tsx
  src/components/navigations/tests/MainTab.test.tsx
Labels: test

#162 [#150]test: 로직 테스트 완료
  jest.setup.ts
  src/app/(home)/_components/MainBanner.tsx
  src/components/auth/tests/ProtectedRoute.test.tsx
  src/components/auth/tests/TokenValidator.test.tsx
  src/components/layout/tests/LoginJoinLayout.test.tsx
  src/hooks/auth/tests/useCheckToken.test.ts
  src/hooks/review/tests/useReviewList.test.tsx
  src/hooks/review/tests/useReviewScore.test.tsx
  src/hooks/tests/useDebounce.test.ts
  src/hooks/useFavorite.ts
  src/stores/tests/useSideBarStore.test.ts
  src/stores/tests/useUserStore.test.ts
  src/utils/test-utils/userMocking.ts
  src/utils/tests/cookieToken.test.ts
Labels: test

#163 [#146]refactor: 마이페이지 액션 컴포넌트 리팩토링
  src/app/mypage/_components/my-card-item/MyCardAction.tsx
  src/app/mypage/_components/my-card-item/actions/MyCardActionGroup.tsx
  src/app/mypage/_components/my-card-item/actions/MyCardCancelButton.tsx
  src/app/mypage/_components/my-card-item/actions/MyCardViewReviewButton.tsx
  src/app/mypage/_components/my-card-item/actions/MyCardWriteReviewButton.tsx
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
  src/app/mypage/_components/tests/MyCardAction.test.tsx
  src/app/mypage/_components/tests/MyCardCancelButton.test.tsx
  src/app/mypage/_components/tests/MyCardList.test.tsx
  src/app/mypage/_components/tests/MyCardViewReviewButton.test.tsx
  src/app/mypage/_components/tests/MyCardWriteReviewButton.test.tsx
  src/app/mypage/_components/tests/MyReviewCardList.test.tsx
  src/utils/test-utils/renderWithClient.tsx
Labels: refactor, test

#165 [#143]test: 공통 컴포넌트 유닛 테스트 & 리팩토링
  src/app/favorites/_components/FavoriteList.tsx
  src/components/common/DeadlineTag.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/common/tests/DeadlineTag.test.tsx
  src/components/common/tests/GatheringFilterSort.test.tsx
  src/components/layout/ClosedMainCardItem.tsx
  src/components/layout/MainCardContent.tsx
  src/components/layout/MainCardImage.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
  src/hooks/useIntersectionObserver.tsx
  src/types/gathering/index.ts
Labels: refactor, test

#166 [#146]test: 마이페이지 및 공통 범위 테스트 작성
  src/app/mypage/_components/tests/MyCardCancelButton.test.tsx
  src/app/mypage/_components/tests/MyCardViewReviewButton.test.tsx
  src/app/mypage/_components/tests/MyCardWriteReviewButton.test.tsx
  src/app/mypage/_components/tests/MyProfile.test.tsx
  src/app/mypage/_components/tests/ReviewTab.test.tsx
  src/components/common/Rating.tsx
  src/components/modals/BackDrop.tsx
  src/components/modals/Modal.tsx
  src/components/modals/create-review-modal/CreateReviewModal.tsx
  src/components/modals/tests/CreateReviewModal.test.tsx
  src/components/modals/tests/EditProfileModal.test.tsx
  src/components/modals/tests/Modal.test.tsx
  src/components/skeletons/MyProfileSkeleton.tsx
  src/hooks/auth/tests/useUpdateUser.test.tsx
  src/hooks/auth/useUpdateUser.ts
  src/utils/test-utils/setupModalRoot.ts
Labels: test

#167 [#143]test: MainCard관련 컴포넌트, utils 유닛 테스트 & 리팩토링
  src/app/favorites/_components/FavoriteList.tsx
  src/components/layout/ClosedMainCardItem.tsx
  src/components/layout/MainCardImage.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
  src/components/layout/tests/MainCardItem.test.tsx
  src/components/layout/tests/MainCardList.test.tsx
  src/utils/gatheringFilterParams.ts
  src/utils/test-utils/gatheringMocking.ts
  src/utils/tests/gatheringFilterParams.test.ts
Labels: test

#168 [#146]refactor: MyProfile 테스트 구조 개선 및 전체 리팩토링
  src/app/mypage/_components/tests/MyProfile.test.tsx
  src/components/modals/create-review-modal/CreateReviewModal.tsx
  src/components/modals/edit-profile-modal/EditProfileModal.tsx
  src/components/modals/tests/EditProfileModal.test.tsx
  src/utils/test-utils/userMocking.ts
Labels: refactor

#170 [#169]design: 모임 목록 페이지, 찜한 목록 페이지 수정
  src/app/favorites/_components/FavoriteList.tsx
  src/app/favorites/layout.tsx
  src/app/gathering/[tab]/_components/Banner.tsx
  src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx
  src/app/gathering/[tab]/layout.tsx
Labels: style

#173 [#143]test: useIntersectionObserver 훅 유닛 테스트
  src/hooks/tests/useIntersectionObserver.test.tsx
  src/utils/test-utils/intersectionObserverTestHelper.ts
Labels: test

#174 [#164]refactor: 기타 코드 수정 및 성능최적화
  __test__/.gitkeep
  public/images/avatar_default.png
  public/images/banner_introduce.png
  public/images/banner_main.png
  public/images/favorite_head.png
  public/images/gathering_default.jpeg
  public/images/gathering_default.png
  public/images/login_join_img.png
  public/images/profile-background.png
  public/images/review_head.png
  src/actions/user-check-action.ts
  src/actions/user-signin-action.ts
  src/actions/user-signup-action.ts
  src/app/(home)/_components/MainCarouselItem.tsx
  src/app/gathering/detail/[id]/_components/GatheringImage.tsx
  src/app/loading.tsx
  src/app/mypage/_components/my-card-item/MyCardImage.tsx
  src/components/layout/MainCardImage.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/ui/Input.tsx
Labels: refactor

#175 [#146]test: CreateReviewModal 테스트 불안정성 개선
  src/app/mypage/page.tsx
  src/components/modals/tests/CreateReviewModal.test.tsx
  src/hooks/review/tests/useCreateReview.test.tsx
  src/hooks/review/useCreateReview.ts
Labels: test

#177 [#164]refactor: 라이트하우스 접근성 점수 개선
  package-lock.json
  package.json
  src/components/common/Rating.tsx
  src/components/navigations/SideBar.tsx
Labels: refactor

#176 [#51]refactor: 번들 최적화
  next.config.mjs
  package-lock.json
  package.json
  public/animations/offline.json
  public/animations/online.json
  src/app/(home)/_components/MainCarouselItem.tsx
  src/app/(home)/_components/MainPromotion.tsx
  src/app/(home)/_components/MainReviewContent.tsx
  src/app/(home)/_components/animations/MainAnimation.tsx
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: refactor

#179 [#51]fix: dynamic import 제거
  src/app/layout.tsx
Labels: fix

#180 [#164]fix: 로그인 불가 이슈 – 토큰 저장 순서 조정으로 해결
  src/actions/user-signin-action.ts
Labels: fix

#183 [#113]fix: Vercel 이미지 최적화 초과로 인한 unoptimized 설정 추가 및 UI 수정
  next.config.mjs
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/_components/my-card-list/MyCreateCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
  src/app/mypage/_components/my-card-list/MyWrittenCardList.tsx
Labels: fix

#185 [#113]fix: 디자인 시안 반영을 위한 UI 일부 수정
  src/app/favorites/_components/FavoriteBanner.tsx
  src/app/gathering/[tab]/_components/Banner.tsx
  src/utils/myCardHelpers.tsx
Labels: fix

#187 [#51]refactor: 이미지 로드 및 UX 개선
  next.config.mjs
  src/app/(home)/_components/MainBanner.tsx
  src/app/(home)/_components/MainCarouselItem.tsx
  src/app/(home)/_components/MainReviewContent.tsx
  src/app/(home)/_components/animations/MainAnimation.tsx
  src/app/gathering/detail/[id]/_components/GatheringImage.tsx
  src/app/layout.tsx
  src/assets/animations/offline.json
  src/assets/animations/online.json
  src/assets/images/main_slide1.jpg
  src/assets/images/main_slide2.jpg
  src/assets/images/main_slide3.jpg
  src/assets/images/main_slide4.jpg
  src/components/layout/MainCardImage.tsx
  src/constants/ui.ts
Labels: refactor

#188 [#143]fix: 모임 카드에서 모바일일 때 좋아요 버튼 레이아웃 깨짐 해결
  src/components/layout/MainCardContent.tsx
Labels: fix

#191 docs: README 업데이트
  README.md
Labels: docs
