Repository codeit-plake/plake, pull requests merged in 2025-03, with the labels that each got.

#7 [#6]chore: setting Storybook and ignore files
  .eslintignore
  .prettierignore
  .storybook/preview.ts
Labels: chore

#9 [#4]feature: favorite component [PLAK-128]
  src/components/common/FavoriteButton.tsx
  src/components/common/stories/FavoriteButton.stories.tsx
  src/components/common/tests/.gitkeep
  src/components/layout/stories/.gitkeep
  src/components/layout/tests/.gitkeep
  src/components/navigations/stories/.gitkeep
  src/components/navigations/tests/.gitkeep
  src/components/providers/stories/.gitkeep
  src/components/providers/tests/.gitkeep
  src/components/skeletons/stories/.gitkeep
  src/components/skeletons/tests/.gitkeep
  src/components/ui/stories/.gitkeep
  src/components/ui/tests/.gitkeep
Labels: feature

#10 [#2]feature: progress bar component [PLAK-119]
  chromatic.config.json
  src/app/page.tsx
  src/components/common/ProgressBar.tsx
  src/stories/ProgressBar.stories.tsx
Labels: feature

#14 [#3]feature: rating component [PLAK-120]
  jest.config.ts
  src/app/page.tsx
  src/components/common/Rating.tsx
  src/components/common/stories/ProgressBar.stories.tsx
  src/components/common/stories/Rating.stories.tsx
  src/components/common/tests/rating.test.ts
  src/utils/rating.ts
Labels: feature

#18 [#11]feature: loading component [PLAK-129]
  src/components/common/FavoriteButton.tsx
  src/components/common/LoadingDots.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/stories/FavoriteButton.stories.tsx
  src/components/common/stories/LoadingDots.stories.tsx
  src/components/common/stories/LoadingSpinner.stories.tsx
Labels: feature

#19 [#15]feature: datetimetag component [PLAK-121]
  src/app/page.tsx
  src/components/common/DateTimeTag.tsx
  src/components/common/stories/DateTimeTag.stories.tsx
  src/components/common/tests/DateTimeTag.test.tsx
Labels: feature

#24 [#20]feature: modal component [PLAK-127]
  src/components/providers/Modal.tsx
  src/components/providers/stories/.gitkeep
  src/components/providers/stories/Modal.stories.tsx
Labels: feature

#26 [#23]feature: button component [PLAK-138]
  src/app/globals.css
  src/app/page.tsx
  src/components/ui/button.tsx
  src/components/ui/stories/button.stories.tsx
  src/components/ui/tests/button.test.tsx
Labels: feature

#32 [#30]feature/30: 모임 상세 페이지 UI 구현 [PLAK-100]
  src/app/gathering/[id]/_components/GatheringInformation.tsx
  src/app/gathering/[id]/_components/GatheringReview.tsx
  src/app/gathering/[id]/index.ts
  src/app/gathering/[id]/page.tsx
  src/components/common/DateTimeTag.tsx
  src/components/common/stories/DateTimeTag.stories.tsx
  src/components/common/tests/DateTimeTag.test.tsx
  src/components/gathering-detail/FloatingBar.tsx
  src/components/gathering-detail/GatheringInformation.tsx
  src/components/gathering-detail/GatheringReviewItem.tsx
  src/components/gathering-detail/GatheringReviewList.tsx
  src/components/gathering-detail/GathetingImage.tsx
  src/components/ui/button.tsx
Labels: design

#33 [#31]feature: DeadlineTag component [PLAK-117]
  src/components/common/DeadlineTag.tsx
  src/components/common/stories/DeadlineTag.stories.tsx
Labels: feature

#34 [#17]feature: MainCardItem component [PLAK-118]
  next.config.mjs
  src/app/gathering/page.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
Labels: feature

#37 [#28]feature: Avatar Component 구현 [PLAK-137]
  package-lock.json
  package.json
  public/favicon.ico
  public/images/.gitkeep
  public/images/avatar_default.png
  public/images/edit-icon.png
  public/images/temp.png
  src/components/common/Avatar.tsx
  src/components/common/Dropdown.tsx
  src/components/common/stories/Avatar.stories.tsx
  src/components/gathering-detail/FloatingBar.tsx
  src/components/layout/Header.tsx
  src/components/navigations/NavList.tsx
  src/components/navigations/SideBar.tsx
  src/components/ui/Popover.tsx
  src/components/ui/calendar.tsx
  src/components/ui/sheet.tsx
  src/components/ui/stories/button.stories.tsx
  src/components/ui/stories/calendar.stories.tsx
  src/components/ui/tests/button.test.tsx
  src/hooks/useCalendar.ts
Labels: feature

#40 [#38]rename: ui컴포넌트 파일명 변경
  src/components/common/tests/.gitkeep
  src/components/ui/Button.tsx
  src/components/ui/Calendar.tsx
  src/components/ui/Select.tsx
  src/components/ui/Sheet.tsx
  src/components/ui/stories/.gitkeep
  src/components/ui/tests/.gitkeep
  src/hooks/.gitkeep
  src/utils/.gitkeep
Labels: rename

#39 [#6]chore: PR 자동화 관련 workflow 설정 추가
  .github/auto_assign.yml
  .github/workflows/.gitkeep
  .github/workflows/pr-automation.yml
  .github/workflows/pr-quality-checks.yml
  package.json
  src/components/providers/Modal.tsx
Labels: chore

#42 [#38]fix: 테스트 에러 수정 시도
  src/app/all-reviews/page.tsx
Labels: fix

#43 [#30]feature: 모임 상세 정보 및 리뷰 데이터 적용 [PLAK-101]
  .env
  .gitignore
  src/app/gathering/[id]/_components/GatheringInformation.tsx
  src/app/gathering/[id]/_components/GatheringReview.tsx
  src/app/gathering/[id]/page.tsx
  src/app/layout.tsx
  src/components/gathering-detail/GatheringImage.tsx
  src/components/gathering-detail/GatheringInformation.tsx
  src/components/gathering-detail/GatheringReviewItem.tsx
  src/components/gathering-detail/GatheringReviewList.tsx
  src/components/gathering-detail/GathetingImage.tsx
  src/components/gathering-detail/ParticipantAvatarStack.tsx
  src/components/providers/QueryProvider.tsx
  src/components/ui/stories/Button.stories.tsx
  src/components/ui/stories/Calendar.stories.tsx
  src/hooks/gathering/useGatheringDetail.ts
  src/hooks/gathering/useParticipants.ts
  src/hooks/review/useReviewList.ts
  src/types/gathering/index.ts
  src/types/review/index.ts
  src/types/user/index.ts
Labels: feature

#46 [#38]feature: Input component 구현 [PLAK-139]
  package-lock.json
  package.json
  src/components/ui/Input.tsx
  src/components/ui/Label.tsx
  src/components/ui/stories/Input.stories.tsx
Labels: feature

#50 [#6]chore: GitHub workflows
  .github/workflows/pr-automation.yml
  .github/workflows/pr-quality-checks.yml
Labels: chore

#45 [#36]feature: GatheringFilterSort 공통 컴포넌트 개발 [PLAK-124]
  src/app/gathering/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FilterCalendar.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/common/stories/Dropdown.stories.tsx
Labels: feature

#52 [#49] feature: Tab component 구현 [PLAK-125]
  src/app/gathering/page.tsx
  src/components/navigations/Tab.tsx
  src/components/navigations/stories/Tab.stories.tsx
  src/constants/ui.ts
  src/hooks/useCustomSearchParams.ts
Labels: feature

#53 [#47]feature: ReviewCardItem,List 컴포넌트 구현 [PLAK-133]
  .env
  package-lock.json
  public/favicon.ico
  src/components/gathering-detail/GatheringReviewItem.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/layout/ReviewCardList.tsx
  src/components/layout/stories/ReviewCardItem.stories.tsx
Labels: feature

#54 [#48]feature: SubTab 컴포넌트 구현 [PLAK-123]
  src/app/gathering/page.tsx
  src/components/navigations/SubTab.tsx
  src/components/navigations/stories/SubTab.stories.tsx
Labels: feature

#55 [#30]feature: 모임 상세페이지 기능 구현 [PLAK-103]
  src/app/error.tsx
  src/app/gathering/[id]/_components/GatheringInformation.tsx
  src/app/gathering/[id]/_components/GatheringReview.tsx
  src/app/gathering/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/[id]/error.tsx
  src/app/gathering/[id]/page.tsx
  src/app/layout.tsx
  src/components/gathering-detail/FloatingBar.tsx
  src/components/gathering-detail/GatheringImage.tsx
  src/components/gathering-detail/GatheringInformation.tsx
  src/components/gathering-detail/ParticipantAvatarStack.tsx
  src/components/skeletons/gathering-detail/GatheringImageSkeleton.tsx
  src/components/skeletons/gathering-detail/GatheringInformationSkeleton.tsx
  src/components/skeletons/gathering-detail/GatheringReviewSkeleton.tsx
  src/components/ui/Skeleton.tsx
  src/constants/gathering.ts
  src/constants/queryKeys.ts
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useGatheringDetail.ts
  src/hooks/gathering/useJoinGathering.ts
  src/hooks/gathering/useParticipants.ts
  src/hooks/review/useReviewList.ts
  src/types/error.ts
  src/types/gathering/index.ts
  src/types/user/index.ts
Labels: feature

#57 [#6]chore: GitHub workflows setting
  .github/workflows/mirror-and-deploy.yml
  package-lock.json
Labels: chore

#59 [HOTFIX] 빌드 에러 디버깅 (useSearchParams)
  src/app/gathering/page.tsx
Labels: fix

#60 [#6]chore: PR workflow에 build 조건 추가
  .github/workflows/pr-quality-checks.yml
  tsconfig.json
Labels: chore

#61 [#51]feature: 모임 만들기 모달 UI 구현 [PLAK-156]
  package-lock.json
  src/app/layout.tsx
  src/components/common/Dropdown.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/layout/stories/ReviewCardItem.stories.tsx
  src/components/modals/Modal.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/DateTimePicker.tsx
  src/components/modals/create-gathering-modal/ImageUploader.tsx
  src/components/modals/create-gathering-modal/ServiceSelector.tsx
  src/components/modals/stories/Modal.stories.tsx
  src/components/providers/ModalProvider.tsx
  src/hooks/gathering/useGatheringDetail.ts
  src/types/gathering/index.ts
  src/types/review/index.ts
  src/types/user/index.ts
Labels: feature

#64 [#63]feature: CardSkeleton 컴포넌트 개발 [PLAKE-130]
  src/components/skeletons/MainCardItemSkeleton.tsx
  src/components/skeletons/ReviewCardItemSkeleton.tsx
  src/components/skeletons/stories/.gitkeep
  src/components/skeletons/stories/MainCardItemSkeleton.stories.tsx
  src/components/skeletons/stories/ReviewCardItemSkeleton.stories.tsx
Labels: feature

#68 [#56]feature: 로그인,회원가입 UI, 유효성 검증 추가 [PLAK-141]
  package-lock.json
  package.json
  public/images/login_join_img.png
  public/images/temp.png
  src/app/globals.css
  src/app/join/page.tsx
  src/app/login/page.tsx
  src/components/common/Avatar.tsx
  src/components/common/stories/Avatar.stories.tsx
  src/components/layout/Header.tsx
  src/components/layout/LoginJoinLayout.tsx
  src/components/navigations/NavList.tsx
  src/components/navigations/SideBar.tsx
  src/components/ui/Input.tsx
  src/constants/.gitkeep
  src/constants/loginJoin.ts
  src/constants/nav.ts
  src/hooks/useDebounce.ts
  src/schemas/.gitkeep
  src/schemas/loginJoinSchema.ts
  src/stores/.gitkeep
  src/stores/useSideBarStore.ts
  src/types/.gitkeep
Labels: feature

#69 [#30]feature: useSuspenseQuery 및 ErrorBoundary 적용
  src/app/error.tsx
  src/app/gathering/[id]/_components/GatheringInformation.tsx
  src/app/gathering/[id]/_components/GatheringInformationWrapper.tsx
  src/app/gathering/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/[id]/_components/GatheringReviewBoardWrapper.tsx
  src/app/gathering/page.tsx
  src/components/gathering-detail/FloatingBar.tsx
  src/components/gathering-detail/GatheringImage.tsx
  src/components/gathering-detail/GatheringInformation.tsx
  src/components/gathering-detail/GatheringReviewItem.tsx
  src/components/gathering-detail/GatheringReviewList.tsx
  src/components/gathering-detail/ParticipantAvatarStack.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
  src/constants/queryKeys.ts
  src/hooks/gathering/useGatheringDetail.ts
  src/hooks/gathering/useParticipants.ts
  src/hooks/review/useReviewList.ts
Labels: feature

#70 [#35] MainCardList 컴포넌트 개발, Service layer 분리 [PLAK-140]
  next.config.mjs
  src/app/gathering/page.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
  src/constants/queryKeys.ts
  src/hooks/gathering/useGatheringList.ts
  src/services/Service.ts
  src/services/gathering/GatheringService.ts
Labels: feature

#71 [Fix] MainTab, SubTab 컴포넌트 관련 수정
  src/app/gathering/_component/FilterTab.tsx
  src/app/gathering/page.tsx
  src/components/navigations/MainTab.tsx
  src/components/navigations/SubTab.tsx
  src/components/navigations/Tab.tsx
  src/components/navigations/stories/MainTab.stories.tsx
  src/components/navigations/stories/SubTab.stories.tsx
  src/constants/ui.ts
Labels: fix

#73 [Fix] FilterTab 이름 및 경로 변경
  src/app/gathering/page.tsx
  src/components/navigations/FilterTab.tsx
Labels: fix

#75 [#72] feature: MainCardList Suspense, ErrorBoundary 적용 [PLAK-176]
  .github/workflows/pr-quality-checks.yml
  src/app/gathering/page.tsx
  src/components/boundary/FetchBoundary.tsx
  src/components/layout/MainCardList.tsx
  src/components/skeletons/MainCardListSkeleton.tsx
  src/components/ui/FetchError.tsx
  src/hooks/gathering/useGatheringList.ts
Labels: feature

#76 [#51]feature: 모달 기능 구현 및 모달 store 생성 [PLAK-178]
  package-lock.json
  src/app/layout.tsx
  src/components/common/Dropdown.tsx
  src/components/gathering-detail/FloatingBar.tsx
  src/components/modals/Modal.tsx
  src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/DateTimeAndEndTimePicker.tsx
  src/components/modals/create-gathering-modal/DateTimePicker.tsx
  src/components/modals/create-gathering-modal/ImageUploader.tsx
  src/components/modals/create-gathering-modal/ServiceSelector.tsx
  src/components/modals/create-gathering-modal/TimePicker.tsx
  src/components/providers/ModalProvider.tsx
  src/components/ui/Calendar.tsx
  src/constants/gathering.ts
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useJoinGathering.ts
  src/hooks/useCalendar.ts
  src/hooks/useClickOutside.ts
  src/schemas/gatheringSchema.ts
  src/stores/useModalStore.ts
Labels: feature

#77 [#67]feature: 마이페이지 모달 UI 작업 [PLAKE-164]
  src/app/mypage/_components/MyProfile.tsx
  src/components/common/Avatar.tsx
  src/components/modals/Modal.tsx
  src/components/modals/create-review-modal/CreateReviewModal.tsx
  src/components/modals/edit-profile-modal/EditProfileModal.tsx
  src/components/ui/Input.tsx
  src/schemas/loginJoinSchema.ts
  src/schemas/profileSchema.ts
  src/schemas/reviewSchema.ts
Labels: feature

#78 [#30]feature: API Instance 적용 및 핸들러 추가
  src/app/gathering/[id]/page.tsx
  src/app/globals.css
  src/components/common/DateTimeTag.tsx
  src/components/common/stories/DateTimeTag.stories.tsx
  src/components/common/stories/Rating.stories.tsx
  src/components/common/tests/DateTimeTag.test.tsx
  src/components/common/tests/__snapshots__/DateTimeTag.test.tsx.snap
  src/components/gathering-detail/FloatingBar.tsx
  src/components/gathering-detail/GatheringInformation.tsx
  src/components/gathering-detail/GatheringReviewItem.tsx
  src/components/gathering-detail/GatheringReviewList.tsx
  src/components/gathering-detail/ParticipantAvatarStack.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/ReviewCardList.tsx
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useGatheringDetail.ts
  src/hooks/gathering/useJoinGathering.ts
  src/hooks/review/useReviewList.ts
  src/services/HttpClient.ts
  src/services/Service.ts
  src/services/gathering/GatheringService.ts
  src/services/review/ReviewService.ts
Labels: feature

#79 [#51]feature: 모임 만들기 유효성 검사 및 hook 구현 [PLAK-178]
  src/app/gathering/layout.tsx
  src/app/layout.tsx
  src/components/common/Dropdown.tsx
  src/components/modals/Modal.tsx
  src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/DateTimePicker.tsx
  src/components/modals/create-gathering-modal/ImageUploader.tsx
  src/components/modals/create-gathering-modal/ServiceSelector.tsx
  src/components/modals/create-gathering-modal/SubServiceSelector.tsx
  src/components/modals/edit-profile-modal/EditProfileModal.tsx
  src/components/providers/ModalProvider.tsx
  src/constants/gathering.ts
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useCreateGathering.ts
  src/hooks/useCalendar.ts
  src/schemas/gatheringSchema.ts
  src/services/gathering/GatheringService.ts
Labels: feature

#81 [#56]feature: 로그인/회원가입 페이지 UI 및 기능 구현 완료 [PLAK-87]
  package-lock.json
  package.json
  public/images/edit-button.png
  src/actions/user-check-action.ts
  src/actions/user-signin-action.ts
  src/actions/user-signup-action.ts
  src/app/all-reviews/page.tsx
  src/app/join/_components/JoinForm.tsx
  src/app/join/page.tsx
  src/app/login/_components/LoginForm.tsx
  src/app/login/page.tsx
  src/components/auth/TokenValidator.tsx
  src/components/common/Avatar.tsx
  src/components/layout/Header.tsx
  src/components/layout/LoginJoinLayout.tsx
  src/components/navigations/NavList.tsx
  src/components/navigations/SideBar.tsx
  src/components/ui/Input.tsx
  src/constants/loginJoin.ts
  src/hooks/auth/useHydrateUserStore.ts
  src/hooks/auth/useLogout.ts
  src/schemas/loginJoinSchema.ts
  src/services/auth/AuthService.ts
  src/stores/useSideBarStore.ts
  src/stores/useUserStore.ts
  src/utils/cookieToken.ts
Labels: feature

#83 [#56]fix: TokenValidator 수정
  src/components/auth/TokenValidator.tsx
Labels: fix

#84 [#80]feature: 메인페이지 UI 및 기능 구현
  package-lock.json
  package.json
  public/images/logo.png
  public/images/main_banner.jpg
  src/app/(home)/_components/DeadLineCarousel.tsx
  src/app/(home)/_components/MainBanner.tsx
  src/app/(home)/_components/MainCarousel.tsx
  src/app/(home)/_components/MainCarouselContainer.tsx
  src/app/(home)/_components/MainCarouselItem.tsx
  src/app/(home)/_components/MainContent.tsx
  src/app/(home)/_components/MainPromotion.tsx
  src/app/(home)/_components/MainPromotionContainer.tsx
  src/app/(home)/_components/MainReviewContent.tsx
  src/app/(home)/_components/MainReviewItem.tsx
  src/app/(home)/_components/PopularCarousel.tsx
  src/app/(home)/index.ts
  src/app/(home)/page.tsx
  src/app/page.tsx
  src/components/boundary/FetchBoundary.tsx
  src/components/providers/QueryProvider.tsx
  src/components/ui/CarouselArrowButton.tsx
  src/constants/queryKeys.ts
  src/constants/review.ts
  src/hooks/gathering/useDeadlineImminentGatherings.ts
  src/hooks/gathering/usePopularGatherings.ts
  src/hooks/useCarouselEdge.ts
Labels: feature

#85 [#80]fix: Swiper 사용 시 SSR 시점에서 스타일 적용되지 않는 문제 해결
  src/app/(home)/_components/MainCarousel.tsx
  src/app/(home)/_components/MainCarouselContainer.tsx
  src/app/(home)/_components/MainCarouselItem.tsx
  src/app/(home)/_components/MainPromotion.tsx
  src/app/gathering/detail/[id]/_components/GatheringInformation.tsx
  src/app/gathering/detail/[id]/_components/GatheringInformationWrapper.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoardWrapper.tsx
  src/app/gathering/detail/[id]/error.tsx
  src/app/gathering/detail/[id]/index.ts
  src/app/gathering/detail/[id]/page.tsx
  src/components/skeletons/MainCarouselSkeleton.tsx
Labels: fix

#86 [#67]feature: 마이페이지 기본 레이아웃 및 프로필 기능 구현
  src/app/mypage/_components/EmptyState.tsx
  src/app/mypage/_components/MyCardList.tsx
  src/app/mypage/_components/MyProfile.tsx
  src/app/mypage/_components/ReviewContent.tsx
  src/app/mypage/_components/ReviewTab.tsx
  src/app/mypage/gathering/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/reviews/page.tsx
  src/components/modals/edit-profile-modal/EditProfileModal.tsx
  src/components/skeletons/MyProfileSkeleton.tsx
  src/components/ui/Input.tsx
  src/constants/queryKeys.ts
  src/constants/ui.ts
  src/hooks/auth/useUpdateUser.ts
  src/hooks/review/useReviewList.ts
  src/schemas/loginJoinSchema.ts
  src/schemas/profileSchema.ts
  src/services/HttpClient.ts
  src/services/auth/AuthService.ts
  src/services/review/ReviewService.ts
  src/types/user/index.ts
Labels: feature

#87 [#72] Feature: 메인 목록 페이지 탭 구현 [PLAK-177]
  next.config.mjs
  public/images/banner_introduce.png
  public/images/banner_main.png
  src/app/gathering/[tab]/_components/Banner.tsx
  src/app/gathering/[tab]/layout.tsx
  src/app/gathering/[tab]/page.tsx
  src/app/gathering/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FilterCalendar.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/navigations/FilterTab.tsx
  src/components/navigations/MainTab.tsx
  src/components/navigations/SubTab.tsx
  src/components/skeletons/MainCardItemSkeleton.tsx
  src/constants/gathering.ts
  src/constants/nav.ts
  src/constants/ui.ts
  src/hooks/gathering/useConvertToQueryStr.ts
  src/hooks/gathering/useGatheringList.ts
  src/hooks/useCustomSearchParams.ts
  src/services/gathering/GatheringService.ts
  src/types/gathering/index.ts
  src/types/gathering/main-tab.ts
Labels: feature

#95 [#51]feature: 모임 만들기 formData 적용 및 기능 수정 [PLAK-156]
  src/app/gathering/[tab]/layout.tsx
  src/app/gathering/layout.tsx
  src/components/modals/Modal.tsx
  src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/DateTimeAndEndTimePicker.tsx
  src/components/modals/create-gathering-modal/DateTimePicker.tsx
  src/components/modals/create-gathering-modal/ImageUploader.tsx
  src/components/modals/create-gathering-modal/ServiceSelector.tsx
  src/components/modals/create-gathering-modal/SubServiceSelector.tsx
  src/components/modals/create-gathering-modal/TimePicker.tsx
  src/components/providers/ModalProvider.tsx
  src/components/ui/Input.tsx
  src/components/ui/stories/Calendar.stories.tsx
  src/constants/gathering.ts
  src/hooks/gathering/useCreateGathering.ts
  src/hooks/useCalendar.ts
  src/schemas/gatheringSchema.ts
  src/services/gathering/GatheringService.ts
  src/utils/form.ts
Labels: feature

#96 [#30]feature: gatheringId로 필터링된 Reviews 데이터 페칭 및 페이지네이션 구현 [PLAK-157]
  src/app/gathering/detail/[id]/_components/FloatingBar.tsx
  src/app/gathering/detail/[id]/_components/GatheringDetailInformation.tsx
  src/app/gathering/detail/[id]/_components/GatheringImage.tsx
  src/app/gathering/detail/[id]/_components/GatheringInformation.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoardWrapper.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewItem.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewList.tsx
  src/app/gathering/detail/[id]/_components/ParticipantAvatarStack.tsx
  src/app/gathering/detail/[id]/page.tsx
  src/components/gathering-detail/GatheringReviewList.tsx
  src/components/ui/Pagination.tsx
  src/constants/queryKeys.ts
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useJoinGathering.ts
  src/hooks/review/useReviewList.ts
  src/hooks/review/useReviewsByGatheringId.ts
  src/hooks/useCopyLink.ts
  src/hooks/useScrollToTop.ts
  src/services/review/ReviewService.ts
  src/types/review/index.ts
Labels: feature

#97 [#72]feature: 모임 목록페이지 무한 스크롤 구현[PLAK-174]
  src/components/common/GatheringFilterSort.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/navigations/MainTab.tsx
  src/components/navigations/SubTab.tsx
  src/constants/gathering.ts
  src/constants/gatheringFilterParams.ts
  src/hooks/gathering/useGatheringFilterParams.ts
  src/hooks/gathering/useGatheringList.ts
  src/hooks/useIntersectionObserver.tsx
  src/services/gathering/GatheringService.ts
Labels: feature

#99 [#67]refactor: MyCardItem 컴포넌트 OCP 원칙 기반으로 리팩토링
  .github/workflows/mirror-and-deploy.yml
  .github/workflows/pr-quality-checks.yml
  src/app/mypage/_components/MyCardItem.tsx
  src/app/mypage/_components/MyCardList.tsx
  src/app/mypage/_components/ReviewContent.tsx
  src/app/mypage/_components/my-card-item/MyCardAction.tsx
  src/app/mypage/_components/my-card-item/MyCardContent.tsx
  src/app/mypage/_components/my-card-item/MyCardImage.tsx
  src/app/mypage/_components/my-card-item/MyCardItem.tsx
  src/app/mypage/_components/my-card-item/MyCardLabels.tsx
  src/app/mypage/_components/my-card-item/MyCardTitle.tsx
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/reviews/page.tsx
  src/components/common/LoadingDots.tsx
  src/constants/queryKeys.ts
  src/hooks/gathering/useMyGatheringList.ts
  src/services/gathering/GatheringService.ts
  src/types/gathering/my-card.ts
  src/utils/myCardHelpers.tsx
Labels: refactor

#98 [#72]feature: 모임 목록페이지 모임 만들기 모달 추가
  src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx
  src/app/gathering/[tab]/layout.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/navigations/FilterTab.tsx
  src/components/navigations/MainTab.tsx
Labels: feature

#100 [#67]refactor: Route Handler 기반 인증 API 요청 구조 적용
  middleware.ts
  src/app/api/user/update/route.ts
  src/app/lib/api/ApiClient.ts
  src/app/lib/api/handleRouteErorr.ts
  src/hooks/auth/useUpdateUser.ts
  src/services/auth/AuthService.ts
  src/services/auth/NonAuthService.ts
Labels: refactor

#104 [#82]feature: 모든 리뷰페이지 개발 완료
  public/images/review_head.png
  src/app/all-reviews/[tab]/_components/ReviewBanner.tsx
  src/app/all-reviews/[tab]/_components/ReviewFilter.tsx
  src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx
  src/app/all-reviews/[tab]/_components/ReviewListParent.tsx
  src/app/all-reviews/[tab]/_components/ReviewRating.tsx
  src/app/all-reviews/[tab]/_components/ReviewSubTab.tsx
  src/app/all-reviews/[tab]/_components/ReviewTab.tsx
  src/app/all-reviews/[tab]/page.tsx
  src/app/all-reviews/layout.tsx
  src/app/all-reviews/page.tsx
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/components/auth/ProtectedRoute.tsx
  src/components/auth/TokenValidator.tsx
  src/components/layout/Header.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/layout/ReviewCardList.tsx
  src/components/navigations/NavList.tsx
  src/components/providers/QueryProvider.tsx
  src/components/skeletons/ReviewCardItemSkeleton.tsx
  src/components/skeletons/ReviewRatingSkeleton.tsx
  src/constants/font.ts
  src/constants/nav.ts
  src/constants/queryKeys.ts
  src/constants/review.ts
  src/hooks/auth/useCheckToken.ts
  src/hooks/auth/useHydrateUserStore.ts
  src/hooks/review/useReviewList.ts
  src/hooks/review/useReviewScore.ts
  src/services/review/AnonReviewService.ts
  src/stores/useUserStore.ts
  src/types/review/index.ts
  src/types/review/score.ts
Labels: feature

#106 [#82]fix: 리뷰페이지 무한스크롤 수정
  src/app/join/_components/JoinForm.tsx
  src/app/login/_components/LoginForm.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/providers/QueryProvider.tsx
  src/components/ui/Input.tsx
  src/hooks/review/useReviewList.ts
  src/types/review/index.ts
Labels: fix

#107 [#30]fix: 코드 구조 및 TimePicker 기능 수정
  package-lock.json
  package.json
  src/app/(home)/_components/MainContent.tsx
  src/app/(home)/_components/MainReviewContent.tsx
  src/app/(home)/_components/MainReviewItem.tsx
  src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx
  src/app/gathering/detail/[id]/_components/FloatingBar.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewList.tsx
  src/app/gathering/detail/[id]/page.tsx
  src/components/modals/create-gathering-modal/DateTimePicker.tsx
  src/components/modals/create-gathering-modal/TimePicker.tsx
  src/components/ui/Pagination.tsx
  src/constants/review.ts
  src/hooks/useCalendar.ts
  src/types/review/main-review.ts
  tailwind.config.ts
Labels: fix

#108 [#72]fix: GATHERING.listByParams 쿼리키에 탭 파라미터 추가 및 마감 모임 필터링[PLAK-89]
  src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx
  src/app/gathering/[tab]/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FilterCalendar.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/navigations/SubTab.tsx
  src/constants/queryKeys.ts
  src/hooks/gathering/useGatheringInfiniteList.ts
  src/services/gathering/AnonGatheringService.ts
  src/stores/useTabStore.ts
  src/utils/gatheringFilterParams.ts
Labels: fix

#109 [#67]feature: 마이페이지 기능 구현 완료
  .github/workflows/mirror-and-deploy.yml
  .github/workflows/pr-quality-checks.yml
  src/app/api/auths/user/route.ts
  src/app/mypage/_components/my-card-list/MyCreateCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
  src/app/mypage/_components/my-card-list/MyWrittenCardList.tsx
  src/app/mypage/gathering/page.tsx
  src/app/mypage/reviews/page.tsx
  src/constants/queryKeys.ts
  src/hooks/auth/useCheckUser.ts
  src/hooks/gathering/useMyGatheringList.ts
  src/services/auth/AuthService.ts
  src/types/gathering/index.ts
Labels: feature

#110 [#82]fix: 기타 css 수정
  src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx
  src/app/all-reviews/[tab]/_components/ReviewSubTab.tsx
  src/app/gathering/detail/[id]/_components/FloatingBar.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx
  src/app/join/_components/JoinForm.tsx
  src/app/login/_components/LoginForm.tsx
  src/assets/.gitkeep
  src/components/common/Avatar.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/layout/ReviewCardItem.tsx
  src/components/modals/Modal.tsx
  src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx
  src/components/navigations/SideBar.tsx
  src/components/ui/Sheet.tsx
Labels: fix

#111 [#102]feature: 모임 찜하기 기능 구현
  src/app/favorites/_components/GatheringFavoriteList.tsx
  src/app/favorites/page.tsx
  src/app/gathering/detail/[id]/_components/GatheringDetailInformation.tsx
  src/components/common/FavoriteButton.tsx
  src/components/common/FavoriteButtonWrapper.tsx
  src/components/layout/MainCardItem.tsx
  src/components/layout/MainCardList.tsx
  src/components/layout/stories/MainCardItem.stories.tsx
Labels: feature

#114 [#113]fix: 전체 서비스 디버깅
  src/app/mypage/layout.tsx
  src/components/common/Rating.tsx
  src/hooks/gathering/useCancelGathering.ts
  src/hooks/gathering/useCreateGathering.ts
  src/hooks/useCalendar.ts
Labels: fix

#115 [#102]feature: ids 기준 찜한 모임 데이터 패칭
  src/app/favorites/_components/FavoriteFilterTab.tsx
  src/app/favorites/_components/FavoriteList.tsx
  src/app/favorites/_components/FavoriteMainTab.tsx
  src/app/favorites/_components/FavoriteSubTab.tsx
  src/app/favorites/_components/GatheringFavoriteList.tsx
  src/app/favorites/layout.tsx
  src/app/favorites/page.tsx
  src/components/common/FavoriteButtonWrapper.tsx
  src/components/navigations/NavList.tsx
  src/constants/favorite.ts
  src/constants/queryKeys.ts
  src/hooks/gathering/useFavoriteList.ts
  src/services/gathering/AnonGatheringService.ts
  src/stores/useFavoriteStore.ts
  src/stores/useTabStore.ts
Labels: feature

#117 fix: 모임 찾기 페이지, 즐겨찾기 페이지 수정
  src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx
  src/app/all-reviews/[tab]/_components/ReviewSubTab.tsx
  src/app/favorites/_components/FavoriteList.tsx
  src/app/mypage/_components/ReviewTab.tsx
  src/components/common/FilterCalendar.tsx
  src/components/common/GatheringFilterSort.tsx
  src/components/layout/MainCardItem.tsx
  src/components/navigations/NavTab.tsx
  src/components/navigations/SubTab.tsx
Labels: fix

#118 [#113]refactor: 리뷰 등록 기능 변경
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
  src/utils/myCardHelpers.tsx
  src/utils/rating.ts
Labels: refactor

#119 [#30]feature: 참여/참여취소 alert 모달 및 유효성 즉시 검사 적용
  src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx
  src/app/gathering/[tab]/layout.tsx
  src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx
  src/app/gathering/detail/[id]/_components/ParticipantAvatarStack.tsx
  src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx
  src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
  src/components/modals/create-gathering-modal/ServiceSelector.tsx
  src/components/ui/Input.tsx
  src/constants/gathering.ts
  src/hooks/gathering/useJoinGathering.ts
  src/schemas/gatheringSchema.ts
Labels: feature

#121 [#113]fix: 삭제된 모임 필터링 로직 추가
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/_components/my-card-list/MyCreateCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
Labels: fix

#123 [#30]fix: dateTime -> registrationEnd 변경
  src/app/gathering/detail/[id]/_components/GatheringImage.tsx
Labels: fix

#124 [#113]refactor: 필터 로직 에러 수정
  src/app/mypage/_components/my-card-list/MyCardList.tsx
  src/app/mypage/_components/my-card-list/MyCreateCardList.tsx
  src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
Labels: refactor
